---
- name: Ansible Task
  hosts: servers
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Create User
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
        state: present

    - name: Mkdir ssh
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0700'

    - name: Generate keys
      openssh_keypair:
        path: "/home/{{ user_name }}/.ssh/id_rsa"
        type: rsa
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
      register: ssh_key

    - name: Create authorized_keys
      copy:
        content: "{{ ssh_key.public_key }}"
        dest: "/home/{{ user_name }}/.ssh/authorized_keys"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: Disable password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backup: yes

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

    - name: mkdir in /opt/
      file:
        path: "/opt/{{ user_name }}"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'
